### ISSUE TITLE
Attempts to delete a VolumeSnapshotContent continually fail

### ISSUE THREAD

**Issue by sventi555** [kubernetes-csi/csi-driver-host-path#203]
I tried to create a VolumeSnapshotContent that references a pre-existing snapshot in DigitalOcean. I then specify that VolumeSnapshotContent resource as a source in a VolumeSnapshot.

When I subsequently tried to delete both resources, the VolumeSnapshotContent did not delete (after being marked for deletion for over 10 minutes).

Here are the resource manifests:

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  name: corner-mongo-snapshot-content
  namespace: corner
spec:
  deletionPolicy: Retain
  driver: hostpath.csi.k8s.io
  source:
    snapshotHandle: f2f3056c-01c8-11eb-9792-0a58ac14e18c
  volumeSnapshotRef:
    name: corner-mongo-snapshot
    namespace: corner
```

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: corner-mongo-snapshot
  namespace: corner
spec:
  source:
    volumeSnapshotContentName: corner-mongo-snapshot-content
```

The snapshot indicated in the `snapshotHandle` exists on my DigitalOcean account.

Thank you!!
