### ISSUE TITLE
failed to provision volume with StorageClass "csi-hostpath-sc": error getting handle for DataSource Type PersistentVolumeClaim by Name pvc-claim-1: claim in dataSource not bound or invalid

### ISSUE THREAD

**Issue by abdelghanimeliani** [kubernetes-csi/csi-driver-host-path#398]
im trying to test the clone functionality of the csi driver , i m folowing [this documentation](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/) :

i created a pv and a pvc and a storage class with the following configurations : 

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-1
  labels:
    type: local
spec:
  storageClassName: csi-hostpath-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
``` 

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-1
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
``` 

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc
provisioner: hostpath.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

```

and i created a new pvc to clone the existing pv content with the folowinf config 

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    namespace: default
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-claim-1
``` 

the pvc was created but it's always in the peding state : 

![image](https://user-images.githubusercontent.com/62490938/222390444-904c32b6-4b54-4845-8f80-c5065ce276b2.png)
